#!/usr/bin/env bash
#
# Start the throwaway Headscale, seed it with users/nodes/tags/routes/policy,
# mint an API key, and write dev/.env.dev.
#
# Idempotent: re-running against an already-seeded instance skips what exists.
# Nothing here touches a production Headscale — it only ever talks to the
# container defined in compose.dev.yaml.

set -euo pipefail

cd "$(dirname "$0")/.."

COMPOSE=(docker compose -f compose.dev.yaml)
HS=("${COMPOSE[@]}" exec -T headscale-dev headscale)
ENV_FILE=dev/.env.dev

# ---------------------------------------------------------------- helpers ---

log() { printf '\033[1;36m==>\033[0m %s\n' "$*"; }

# hskey-authreq- (14) + 24 random chars = the 38 bytes types.AuthID validates.
auth_id() {
  printf 'hskey-authreq-%s' \
    "$(LC_ALL=C tr -dc 'A-Za-z0-9' </dev/urandom | head -c 24)"
}

user_exists() {
  "${HS[@]}" users list --output json 2>/dev/null \
    | grep -q "\"name\":[[:space:]]*\"$1\""
}

node_id() {
  "${HS[@]}" nodes list --output json 2>/dev/null \
    | python3 -c "
import json,sys
name=sys.argv[1]
for n in json.load(sys.stdin) or []:
    if n.get('name')==name or n.get('givenName')==name:
        print(n['id']); break
" "$1"
}

# Create a node without a real Tailscale client. 'debug create-node' registers a
# pending auth request; 'auth register' completes it against a user.
seed_node() {
  local name=$1 user=$2
  shift 2
  if [[ -n "$(node_id "$name")" ]]; then
    log "node $name exists, skipping"
    return
  fi
  local id
  id=$(auth_id)
  local route_args=()
  for r in "$@"; do route_args+=(--route "$r"); done
  # macOS ships bash 3.2, where "${arr[@]}" on an empty array trips `set -u`.
  "${HS[@]}" debug create-node --name "$name" --user "$user" --key "$id" \
    ${route_args[@]+"${route_args[@]}"} >/dev/null
  "${HS[@]}" auth register --user "$user" --auth-id "$id" >/dev/null
  log "node $name → $user${1+ (routes: $*)}"
}

# ------------------------------------------------------------------- start ---

log "starting throwaway Headscale (compose.dev.yaml)"
"${COMPOSE[@]}" up -d --wait

# ------------------------------------------------------------------- users ---

for u in alice bob ops; do
  if user_exists "$u"; then
    log "user $u exists, skipping"
  else
    "${HS[@]}" users create "$u" --email "$u@headboard.test" \
      --display-name "$(tr '[:lower:]' '[:upper:]' <<<"${u:0:1}")${u:1}" >/dev/null
    log "user $u"
  fi
done

# -------------------------------------------------------------- policy set ---
# Before tagging: tag:prod / tag:ci must have owners or the tag is rejected.

log "applying dev/policy.hujson"
"${COMPOSE[@]}" cp dev/policy.hujson headscale-dev:/tmp/policy.hujson
"${HS[@]}" policy set --file /tmp/policy.hujson

# ------------------------------------------------------------------- nodes ---

seed_node alice-laptop alice
seed_node alice-phone alice
seed_node bob-desktop bob
seed_node ops-gw ops 10.0.0.0/24 0.0.0.0/0 ::/0
seed_node prod-web ops

# ------------------------------------------------- routes and tags on nodes ---

GW_ID=$(node_id ops-gw)
if [[ -n "$GW_ID" ]]; then
  "${HS[@]}" nodes approve-routes --identifier "$GW_ID" \
    --routes "10.0.0.0/24,0.0.0.0/0,::/0" >/dev/null
  log "ops-gw: approved subnet route + exit node"
fi

WEB_ID=$(node_id prod-web)
if [[ -n "$WEB_ID" ]]; then
  "${HS[@]}" nodes tag --identifier "$WEB_ID" --tags tag:prod >/dev/null
  log "prod-web: tagged tag:prod"
fi

# ----------------------------------------------------------------- api key ---
# Reuse an existing unexpired key if dev/.env.dev already has one — the secret
# is only ever printed at creation time.

if [[ -f "$ENV_FILE" ]] && grep -q '^HEADSCALE_API_KEY=hskey-api-' "$ENV_FILE"; then
  log "$ENV_FILE already has an API key, keeping it"
else
  KEY=$("${HS[@]}" apikeys create --expiration 90d | tail -n1 | tr -d '\r')
  cat >"$ENV_FILE" <<EOF
# Generated by dev/up.sh — throwaway stack only. Safe to delete.
# None of these credentials are worth anything outside the local containers.
HEADSCALE_URL=http://127.0.0.1:8080
HEADSCALE_API_KEY=$KEY
HEADBOARD_POLL_INTERVAL=5s
HEADBOARD_DEV=true

# Headboard's own store, next to the repo. Delete the file to start over.
DATABASE_URL=dev/headboard.db

HEADBOARD_PUBLIC_URL=http://127.0.0.1:3000
OIDC_ISSUER=http://127.0.0.1:9998/oidc
OIDC_CLIENT_ID=headboard-dev
OIDC_CLIENT_SECRET=headboard-dev-secret
EOF
  log "wrote $ENV_FILE"
fi

# ------------------------------------------------------------------ verify ---

log "seeded state:"
"${HS[@]}" users list
"${HS[@]}" nodes list

cat <<EOF

Dev stack up:
  Headscale  http://127.0.0.1:8080   (policy.mode=database)
  Headboard's own store is dev/headboard.db — delete it to start over.

  Start the dev identity provider in its own terminal:
    ./dev/mockoidc.sh

  Run Headboard against it:
    env \$(grep -v '^#' $ENV_FILE | xargs) go run ./cmd/headboard

  Capture golden fixtures for T2:
    ./dev/fixtures.sh

  Tear it down (destroys the volume):
    ./dev/down.sh
EOF
